version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
    - discovery.type=single-node
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"

  filebeat:
    container_name: filebeat
    build:
      context: ./infra/
      dockerfile: Dockerfile
    user: root
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    command: ["filebeat", "-e"]
    depends_on:
    - elasticsearch

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - filebeat

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - backend
volumes:
  esdata:
    driver: local

